# 由 luckfox_add_compile_check() 以 cmake -P 调用：逐个以 -c -o /dev/null 编译 SOURCES，任一失败即以非 0 退出。
string(REPLACE "|" ";" flags "${FLAGS}")
string(REPLACE "|" ";" sources "${SOURCES}")
set(failed 0)
foreach(src IN LISTS sources)
    execute_process(COMMAND ${CC} ${flags} -c ${src} -o /dev/null RESULT_VARIABLE rc)
    if(rc EQUAL 0)
        message("PASS ${src}")
    else()
        message("FAIL ${src}")
        set(failed 1)
    endif()
endforeach()
if(failed)
    message(FATAL_ERROR "compile check failed")
endif()
